//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/InputActions/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""37c91041-65b1-4399-b28f-561bf40984a2"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""85f21fce-e799-4f3d-b2d6-8258af460c6c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotation"",
                    ""type"": ""Value"",
                    ""id"": ""c507aa4a-5d28-4c00-a42f-f8bc5cc16944"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""98b1a6b5-4a13-41e3-b793-87f3397fa48c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""894730e4-1f21-490f-8c17-fb47e8e16abf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WeaponSwapLeft"",
                    ""type"": ""Button"",
                    ""id"": ""f22e1bd9-824d-4488-992d-cb0535ff38c8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WeaponSwapRight"",
                    ""type"": ""Button"",
                    ""id"": ""df38ded9-03a1-460b-a9c1-0357be916f0e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""c7c10386-0f10-4214-9341-1a01dc41c019"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AimPosition"",
                    ""type"": ""Value"",
                    ""id"": ""8d2f477c-762d-477c-8272-ba5f3344051d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DownMotion"",
                    ""type"": ""Button"",
                    ""id"": ""77009459-8686-44e7-8c72-3c198c60b9ed"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UpMotion"",
                    ""type"": ""Button"",
                    ""id"": ""cea53d60-0600-4b54-bf22-5cb894ff50a7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightMotion"",
                    ""type"": ""Button"",
                    ""id"": ""6dc9204f-0f90-4eb2-b564-33a3f1c1dd99"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""MultiTap(pressPoint=1.401298E-45)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftMotion"",
                    ""type"": ""Button"",
                    ""id"": ""d93727c0-bba5-484e-9585-0b84ce80d976"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""MultiTap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Recall"",
                    ""type"": ""Button"",
                    ""id"": ""cf037e2a-938f-4290-88e1-983faa509c28"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""8eefb1a6-b3ba-4865-9aeb-71546b3b6092"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AimPositionGamepad"",
                    ""type"": ""Value"",
                    ""id"": ""ab845d1c-ba72-4120-81e9-78794a438e68"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""333d6e17-0ef8-4531-a116-a0cbcd0a51ff"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""84307615-2860-4795-9173-b32c1b4bc8b4"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""44a39093-aaba-43c0-90ec-ddce47132841"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""e3e7ae8d-88e7-492c-8592-8092658985e3"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""210fccb4-73b7-4943-8e03-4fcbaee3f46a"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ce21cd92-be59-4a05-ae93-273e77cd27b1"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""37c2113f-6f0d-4078-9d08-d87761943134"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b87d9110-5aa3-4c0d-8ea8-7fdd3826234c"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5c832830-4205-4df8-96ba-60be1d20ffa5"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""286837fa-2e8a-4665-abfc-3ce6de6aa69a"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""1210d2c1-bc5d-428d-a885-36c1eeb1b369"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""2ebebd0d-aa0b-44a7-8272-8e7082d14d7f"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d19e1c84-8881-43ab-a930-ab515a3ea209"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""1867c093-6728-43cc-a053-515fb1ed3458"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""0514a7b1-0837-46bb-9a39-41d9f24aaef8"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""92d53f87-66dd-4dae-a797-f093ce82c59a"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd1cf6b3-ec40-42c6-a671-31679bd1bfe4"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0727fbe4-561f-4107-8cde-a5b4b887dddc"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""08f1fe51-77b4-4ba7-962a-f8d5dffc4480"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""57a85715-4bbf-4bbb-a803-84e70d68ecc1"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""WeaponSwapLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""046160e5-3e43-44b1-880d-270d6375ec58"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""WeaponSwapLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b2465bb-289a-4bea-8d8b-13cf3c40f027"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""WeaponSwapRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ecfc3a64-525f-441e-a17d-2920613a3e9a"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""WeaponSwapRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9fa4067d-c857-4a4e-a9d6-5ba338b90a97"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e2d38263-5d2b-4007-b700-4e3ab29c6c5d"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e8fc4d89-bc58-47e8-a4e0-dd0cabeb294d"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""AimPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e3acdf9e-e6e0-4ce4-9b41-4d50c6badee7"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""DownMotion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""474dccac-e0ad-4b14-9e01-43c88f1454b0"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""DownMotion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1e3b230-7475-402a-8258-4e971eb74046"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""UpMotion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b198bd75-c11a-4827-b5f2-c09586c465b7"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""UpMotion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""df587f6a-2871-4602-9340-beffb1a75160"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Recall"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cfc3d591-6b04-4e35-9bf7-88c7aa56c227"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Recall"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2e0b8aa8-cff0-420b-9853-97133a74b617"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d7a06b03-2e4f-468a-a8dc-97517ddac550"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9532dda2-a97b-4efd-9e3c-d24edbe0e08a"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone,ScaleVector2(x=4,y=4)"",
                    ""groups"": ""Gamepad"",
                    ""action"": ""AimPositionGamepad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f9c59282-7bb9-4e0c-966f-0154e28c4152"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""RightMotion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dbf05b55-843f-4d8c-b89d-19a5302c4691"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""RightMotion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""217f87e5-f020-4a5f-affa-4ac1621cb795"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""LeftMotion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ca80137e-5a16-4498-b5a5-994fdb57dab8"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""LeftMotion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a32c5624-3466-4f48-8abc-92ce39c9521d"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""76d44cd9-88a8-4f3b-a2d5-a3235249c633"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PauseMenu"",
            ""id"": ""710e2d5d-d235-4d94-a7af-c6ca7562f855"",
            ""actions"": [
                {
                    ""name"": ""UnPause"",
                    ""type"": ""Button"",
                    ""id"": ""109f65bb-d99f-4eec-bb12-a395e81396c9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeMenuLeft"",
                    ""type"": ""Button"",
                    ""id"": ""98b50ab5-4bc1-4003-bd8e-771b2daf53e8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeMenuRight"",
                    ""type"": ""Button"",
                    ""id"": ""50165b3f-5c17-4059-88a3-bd955f5ced3d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveMapRight"",
                    ""type"": ""Button"",
                    ""id"": ""578361d5-a1fe-4aaf-a349-cc2852c5736c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveMapLeft"",
                    ""type"": ""Button"",
                    ""id"": ""03456a85-8daf-4a00-b675-2244f3067bbb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveMapUp"",
                    ""type"": ""Button"",
                    ""id"": ""68d961d0-bc34-411f-bd85-ec811409c399"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveMapDown"",
                    ""type"": ""Button"",
                    ""id"": ""6965e0e2-92f7-44cc-aa36-abfe1d84099d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EnableMapMovement"",
                    ""type"": ""Button"",
                    ""id"": ""4858c830-cb7d-4c48-95f4-cc922dfb2520"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0226af1e-a7c2-4eb1-9da9-d90bf9147a7d"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""UnPause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f080e02f-aa81-49cd-8579-93b9550fb9a9"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""UnPause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d7d24eb3-04d4-468b-892b-2b8a4759ef15"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""ChangeMenuLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""39d26b84-28e4-438e-94f0-846f40001a46"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""ChangeMenuLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d7ebc531-d995-4be1-84ad-c2f229a0c089"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""ChangeMenuRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d073eefd-a993-4400-8e22-266606ec5423"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""ChangeMenuRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ca45f38d-8a73-46bf-ba8c-56f83bff7d8a"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""MoveMapRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f16f7eb-185a-4bfc-a412-214db7ba4ff5"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""MoveMapLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""efced304-1451-414a-9211-cbc8d536ac44"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""MoveMapUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4817149c-b1f3-4628-9007-6ad05ba38123"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""MoveMapDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""27f95722-e2cb-4efe-b968-6b55c5d8d10b"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""MoveMapLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1757849-9085-4fa8-93e0-1e563f31abb9"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""MoveMapRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e5595a3b-ed0e-485f-8101-bfac0cada733"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""MoveMapUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""72c27107-040e-4b96-b245-3dace613024a"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""MoveMapDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""92a1113d-d2c4-4d01-a8c1-382de5f1460d"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""EnableMapMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9c99888d-814a-46b5-aa6a-8ff2e351a518"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""EnableMapMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""NoInput"",
            ""id"": ""3d137776-f2f6-4960-b903-4773d46ff092"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""5f369a87-d5e3-4fe4-b5c8-690390327c33"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""27885723-0863-45b8-a51f-a401048a818c"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Movement = m_Player.FindAction("Movement", throwIfNotFound: true);
        m_Player_Rotation = m_Player.FindAction("Rotation", throwIfNotFound: true);
        m_Player_Sprint = m_Player.FindAction("Sprint", throwIfNotFound: true);
        m_Player_Shoot = m_Player.FindAction("Shoot", throwIfNotFound: true);
        m_Player_WeaponSwapLeft = m_Player.FindAction("WeaponSwapLeft", throwIfNotFound: true);
        m_Player_WeaponSwapRight = m_Player.FindAction("WeaponSwapRight", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_AimPosition = m_Player.FindAction("AimPosition", throwIfNotFound: true);
        m_Player_DownMotion = m_Player.FindAction("DownMotion", throwIfNotFound: true);
        m_Player_UpMotion = m_Player.FindAction("UpMotion", throwIfNotFound: true);
        m_Player_RightMotion = m_Player.FindAction("RightMotion", throwIfNotFound: true);
        m_Player_LeftMotion = m_Player.FindAction("LeftMotion", throwIfNotFound: true);
        m_Player_Recall = m_Player.FindAction("Recall", throwIfNotFound: true);
        m_Player_Pause = m_Player.FindAction("Pause", throwIfNotFound: true);
        m_Player_AimPositionGamepad = m_Player.FindAction("AimPositionGamepad", throwIfNotFound: true);
        m_Player_Dash = m_Player.FindAction("Dash", throwIfNotFound: true);
        // PauseMenu
        m_PauseMenu = asset.FindActionMap("PauseMenu", throwIfNotFound: true);
        m_PauseMenu_UnPause = m_PauseMenu.FindAction("UnPause", throwIfNotFound: true);
        m_PauseMenu_ChangeMenuLeft = m_PauseMenu.FindAction("ChangeMenuLeft", throwIfNotFound: true);
        m_PauseMenu_ChangeMenuRight = m_PauseMenu.FindAction("ChangeMenuRight", throwIfNotFound: true);
        m_PauseMenu_MoveMapRight = m_PauseMenu.FindAction("MoveMapRight", throwIfNotFound: true);
        m_PauseMenu_MoveMapLeft = m_PauseMenu.FindAction("MoveMapLeft", throwIfNotFound: true);
        m_PauseMenu_MoveMapUp = m_PauseMenu.FindAction("MoveMapUp", throwIfNotFound: true);
        m_PauseMenu_MoveMapDown = m_PauseMenu.FindAction("MoveMapDown", throwIfNotFound: true);
        m_PauseMenu_EnableMapMovement = m_PauseMenu.FindAction("EnableMapMovement", throwIfNotFound: true);
        // NoInput
        m_NoInput = asset.FindActionMap("NoInput", throwIfNotFound: true);
        m_NoInput_Newaction = m_NoInput.FindAction("New action", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Movement;
    private readonly InputAction m_Player_Rotation;
    private readonly InputAction m_Player_Sprint;
    private readonly InputAction m_Player_Shoot;
    private readonly InputAction m_Player_WeaponSwapLeft;
    private readonly InputAction m_Player_WeaponSwapRight;
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_AimPosition;
    private readonly InputAction m_Player_DownMotion;
    private readonly InputAction m_Player_UpMotion;
    private readonly InputAction m_Player_RightMotion;
    private readonly InputAction m_Player_LeftMotion;
    private readonly InputAction m_Player_Recall;
    private readonly InputAction m_Player_Pause;
    private readonly InputAction m_Player_AimPositionGamepad;
    private readonly InputAction m_Player_Dash;
    public struct PlayerActions
    {
        private @PlayerInputActions m_Wrapper;
        public PlayerActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Player_Movement;
        public InputAction @Rotation => m_Wrapper.m_Player_Rotation;
        public InputAction @Sprint => m_Wrapper.m_Player_Sprint;
        public InputAction @Shoot => m_Wrapper.m_Player_Shoot;
        public InputAction @WeaponSwapLeft => m_Wrapper.m_Player_WeaponSwapLeft;
        public InputAction @WeaponSwapRight => m_Wrapper.m_Player_WeaponSwapRight;
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        public InputAction @AimPosition => m_Wrapper.m_Player_AimPosition;
        public InputAction @DownMotion => m_Wrapper.m_Player_DownMotion;
        public InputAction @UpMotion => m_Wrapper.m_Player_UpMotion;
        public InputAction @RightMotion => m_Wrapper.m_Player_RightMotion;
        public InputAction @LeftMotion => m_Wrapper.m_Player_LeftMotion;
        public InputAction @Recall => m_Wrapper.m_Player_Recall;
        public InputAction @Pause => m_Wrapper.m_Player_Pause;
        public InputAction @AimPositionGamepad => m_Wrapper.m_Player_AimPositionGamepad;
        public InputAction @Dash => m_Wrapper.m_Player_Dash;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Rotation.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRotation;
                @Rotation.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRotation;
                @Rotation.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRotation;
                @Sprint.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSprint;
                @Sprint.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSprint;
                @Sprint.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSprint;
                @Shoot.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot;
                @Shoot.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot;
                @Shoot.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot;
                @WeaponSwapLeft.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWeaponSwapLeft;
                @WeaponSwapLeft.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWeaponSwapLeft;
                @WeaponSwapLeft.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWeaponSwapLeft;
                @WeaponSwapRight.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWeaponSwapRight;
                @WeaponSwapRight.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWeaponSwapRight;
                @WeaponSwapRight.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWeaponSwapRight;
                @Jump.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @AimPosition.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAimPosition;
                @AimPosition.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAimPosition;
                @AimPosition.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAimPosition;
                @DownMotion.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDownMotion;
                @DownMotion.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDownMotion;
                @DownMotion.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDownMotion;
                @UpMotion.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnUpMotion;
                @UpMotion.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnUpMotion;
                @UpMotion.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnUpMotion;
                @RightMotion.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRightMotion;
                @RightMotion.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRightMotion;
                @RightMotion.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRightMotion;
                @LeftMotion.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeftMotion;
                @LeftMotion.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeftMotion;
                @LeftMotion.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeftMotion;
                @Recall.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRecall;
                @Recall.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRecall;
                @Recall.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRecall;
                @Pause.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPause;
                @AimPositionGamepad.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAimPositionGamepad;
                @AimPositionGamepad.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAimPositionGamepad;
                @AimPositionGamepad.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAimPositionGamepad;
                @Dash.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDash;
                @Dash.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDash;
                @Dash.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDash;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Rotation.started += instance.OnRotation;
                @Rotation.performed += instance.OnRotation;
                @Rotation.canceled += instance.OnRotation;
                @Sprint.started += instance.OnSprint;
                @Sprint.performed += instance.OnSprint;
                @Sprint.canceled += instance.OnSprint;
                @Shoot.started += instance.OnShoot;
                @Shoot.performed += instance.OnShoot;
                @Shoot.canceled += instance.OnShoot;
                @WeaponSwapLeft.started += instance.OnWeaponSwapLeft;
                @WeaponSwapLeft.performed += instance.OnWeaponSwapLeft;
                @WeaponSwapLeft.canceled += instance.OnWeaponSwapLeft;
                @WeaponSwapRight.started += instance.OnWeaponSwapRight;
                @WeaponSwapRight.performed += instance.OnWeaponSwapRight;
                @WeaponSwapRight.canceled += instance.OnWeaponSwapRight;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @AimPosition.started += instance.OnAimPosition;
                @AimPosition.performed += instance.OnAimPosition;
                @AimPosition.canceled += instance.OnAimPosition;
                @DownMotion.started += instance.OnDownMotion;
                @DownMotion.performed += instance.OnDownMotion;
                @DownMotion.canceled += instance.OnDownMotion;
                @UpMotion.started += instance.OnUpMotion;
                @UpMotion.performed += instance.OnUpMotion;
                @UpMotion.canceled += instance.OnUpMotion;
                @RightMotion.started += instance.OnRightMotion;
                @RightMotion.performed += instance.OnRightMotion;
                @RightMotion.canceled += instance.OnRightMotion;
                @LeftMotion.started += instance.OnLeftMotion;
                @LeftMotion.performed += instance.OnLeftMotion;
                @LeftMotion.canceled += instance.OnLeftMotion;
                @Recall.started += instance.OnRecall;
                @Recall.performed += instance.OnRecall;
                @Recall.canceled += instance.OnRecall;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
                @AimPositionGamepad.started += instance.OnAimPositionGamepad;
                @AimPositionGamepad.performed += instance.OnAimPositionGamepad;
                @AimPositionGamepad.canceled += instance.OnAimPositionGamepad;
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // PauseMenu
    private readonly InputActionMap m_PauseMenu;
    private IPauseMenuActions m_PauseMenuActionsCallbackInterface;
    private readonly InputAction m_PauseMenu_UnPause;
    private readonly InputAction m_PauseMenu_ChangeMenuLeft;
    private readonly InputAction m_PauseMenu_ChangeMenuRight;
    private readonly InputAction m_PauseMenu_MoveMapRight;
    private readonly InputAction m_PauseMenu_MoveMapLeft;
    private readonly InputAction m_PauseMenu_MoveMapUp;
    private readonly InputAction m_PauseMenu_MoveMapDown;
    private readonly InputAction m_PauseMenu_EnableMapMovement;
    public struct PauseMenuActions
    {
        private @PlayerInputActions m_Wrapper;
        public PauseMenuActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @UnPause => m_Wrapper.m_PauseMenu_UnPause;
        public InputAction @ChangeMenuLeft => m_Wrapper.m_PauseMenu_ChangeMenuLeft;
        public InputAction @ChangeMenuRight => m_Wrapper.m_PauseMenu_ChangeMenuRight;
        public InputAction @MoveMapRight => m_Wrapper.m_PauseMenu_MoveMapRight;
        public InputAction @MoveMapLeft => m_Wrapper.m_PauseMenu_MoveMapLeft;
        public InputAction @MoveMapUp => m_Wrapper.m_PauseMenu_MoveMapUp;
        public InputAction @MoveMapDown => m_Wrapper.m_PauseMenu_MoveMapDown;
        public InputAction @EnableMapMovement => m_Wrapper.m_PauseMenu_EnableMapMovement;
        public InputActionMap Get() { return m_Wrapper.m_PauseMenu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PauseMenuActions set) { return set.Get(); }
        public void SetCallbacks(IPauseMenuActions instance)
        {
            if (m_Wrapper.m_PauseMenuActionsCallbackInterface != null)
            {
                @UnPause.started -= m_Wrapper.m_PauseMenuActionsCallbackInterface.OnUnPause;
                @UnPause.performed -= m_Wrapper.m_PauseMenuActionsCallbackInterface.OnUnPause;
                @UnPause.canceled -= m_Wrapper.m_PauseMenuActionsCallbackInterface.OnUnPause;
                @ChangeMenuLeft.started -= m_Wrapper.m_PauseMenuActionsCallbackInterface.OnChangeMenuLeft;
                @ChangeMenuLeft.performed -= m_Wrapper.m_PauseMenuActionsCallbackInterface.OnChangeMenuLeft;
                @ChangeMenuLeft.canceled -= m_Wrapper.m_PauseMenuActionsCallbackInterface.OnChangeMenuLeft;
                @ChangeMenuRight.started -= m_Wrapper.m_PauseMenuActionsCallbackInterface.OnChangeMenuRight;
                @ChangeMenuRight.performed -= m_Wrapper.m_PauseMenuActionsCallbackInterface.OnChangeMenuRight;
                @ChangeMenuRight.canceled -= m_Wrapper.m_PauseMenuActionsCallbackInterface.OnChangeMenuRight;
                @MoveMapRight.started -= m_Wrapper.m_PauseMenuActionsCallbackInterface.OnMoveMapRight;
                @MoveMapRight.performed -= m_Wrapper.m_PauseMenuActionsCallbackInterface.OnMoveMapRight;
                @MoveMapRight.canceled -= m_Wrapper.m_PauseMenuActionsCallbackInterface.OnMoveMapRight;
                @MoveMapLeft.started -= m_Wrapper.m_PauseMenuActionsCallbackInterface.OnMoveMapLeft;
                @MoveMapLeft.performed -= m_Wrapper.m_PauseMenuActionsCallbackInterface.OnMoveMapLeft;
                @MoveMapLeft.canceled -= m_Wrapper.m_PauseMenuActionsCallbackInterface.OnMoveMapLeft;
                @MoveMapUp.started -= m_Wrapper.m_PauseMenuActionsCallbackInterface.OnMoveMapUp;
                @MoveMapUp.performed -= m_Wrapper.m_PauseMenuActionsCallbackInterface.OnMoveMapUp;
                @MoveMapUp.canceled -= m_Wrapper.m_PauseMenuActionsCallbackInterface.OnMoveMapUp;
                @MoveMapDown.started -= m_Wrapper.m_PauseMenuActionsCallbackInterface.OnMoveMapDown;
                @MoveMapDown.performed -= m_Wrapper.m_PauseMenuActionsCallbackInterface.OnMoveMapDown;
                @MoveMapDown.canceled -= m_Wrapper.m_PauseMenuActionsCallbackInterface.OnMoveMapDown;
                @EnableMapMovement.started -= m_Wrapper.m_PauseMenuActionsCallbackInterface.OnEnableMapMovement;
                @EnableMapMovement.performed -= m_Wrapper.m_PauseMenuActionsCallbackInterface.OnEnableMapMovement;
                @EnableMapMovement.canceled -= m_Wrapper.m_PauseMenuActionsCallbackInterface.OnEnableMapMovement;
            }
            m_Wrapper.m_PauseMenuActionsCallbackInterface = instance;
            if (instance != null)
            {
                @UnPause.started += instance.OnUnPause;
                @UnPause.performed += instance.OnUnPause;
                @UnPause.canceled += instance.OnUnPause;
                @ChangeMenuLeft.started += instance.OnChangeMenuLeft;
                @ChangeMenuLeft.performed += instance.OnChangeMenuLeft;
                @ChangeMenuLeft.canceled += instance.OnChangeMenuLeft;
                @ChangeMenuRight.started += instance.OnChangeMenuRight;
                @ChangeMenuRight.performed += instance.OnChangeMenuRight;
                @ChangeMenuRight.canceled += instance.OnChangeMenuRight;
                @MoveMapRight.started += instance.OnMoveMapRight;
                @MoveMapRight.performed += instance.OnMoveMapRight;
                @MoveMapRight.canceled += instance.OnMoveMapRight;
                @MoveMapLeft.started += instance.OnMoveMapLeft;
                @MoveMapLeft.performed += instance.OnMoveMapLeft;
                @MoveMapLeft.canceled += instance.OnMoveMapLeft;
                @MoveMapUp.started += instance.OnMoveMapUp;
                @MoveMapUp.performed += instance.OnMoveMapUp;
                @MoveMapUp.canceled += instance.OnMoveMapUp;
                @MoveMapDown.started += instance.OnMoveMapDown;
                @MoveMapDown.performed += instance.OnMoveMapDown;
                @MoveMapDown.canceled += instance.OnMoveMapDown;
                @EnableMapMovement.started += instance.OnEnableMapMovement;
                @EnableMapMovement.performed += instance.OnEnableMapMovement;
                @EnableMapMovement.canceled += instance.OnEnableMapMovement;
            }
        }
    }
    public PauseMenuActions @PauseMenu => new PauseMenuActions(this);

    // NoInput
    private readonly InputActionMap m_NoInput;
    private INoInputActions m_NoInputActionsCallbackInterface;
    private readonly InputAction m_NoInput_Newaction;
    public struct NoInputActions
    {
        private @PlayerInputActions m_Wrapper;
        public NoInputActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_NoInput_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_NoInput; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(NoInputActions set) { return set.Get(); }
        public void SetCallbacks(INoInputActions instance)
        {
            if (m_Wrapper.m_NoInputActionsCallbackInterface != null)
            {
                @Newaction.started -= m_Wrapper.m_NoInputActionsCallbackInterface.OnNewaction;
                @Newaction.performed -= m_Wrapper.m_NoInputActionsCallbackInterface.OnNewaction;
                @Newaction.canceled -= m_Wrapper.m_NoInputActionsCallbackInterface.OnNewaction;
            }
            m_Wrapper.m_NoInputActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Newaction.started += instance.OnNewaction;
                @Newaction.performed += instance.OnNewaction;
                @Newaction.canceled += instance.OnNewaction;
            }
        }
    }
    public NoInputActions @NoInput => new NoInputActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnRotation(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnShoot(InputAction.CallbackContext context);
        void OnWeaponSwapLeft(InputAction.CallbackContext context);
        void OnWeaponSwapRight(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnAimPosition(InputAction.CallbackContext context);
        void OnDownMotion(InputAction.CallbackContext context);
        void OnUpMotion(InputAction.CallbackContext context);
        void OnRightMotion(InputAction.CallbackContext context);
        void OnLeftMotion(InputAction.CallbackContext context);
        void OnRecall(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnAimPositionGamepad(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
    }
    public interface IPauseMenuActions
    {
        void OnUnPause(InputAction.CallbackContext context);
        void OnChangeMenuLeft(InputAction.CallbackContext context);
        void OnChangeMenuRight(InputAction.CallbackContext context);
        void OnMoveMapRight(InputAction.CallbackContext context);
        void OnMoveMapLeft(InputAction.CallbackContext context);
        void OnMoveMapUp(InputAction.CallbackContext context);
        void OnMoveMapDown(InputAction.CallbackContext context);
        void OnEnableMapMovement(InputAction.CallbackContext context);
    }
    public interface INoInputActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
}
